services:
  wallos:
    image: bellamy/wallos:latest
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/docker-compose/wallos/db:/var/www/html/db
      - /data/docker-compose/wallos/logos:/var/www/html/images/uploads/logos
    networks:
      traefik:
    labels:
      - traefik.enable=true
      - traefik.http.routers.wallos.rule=Host(`wallos.imbytecat.com`)
      - traefik.http.services.wallos.loadbalancer.server.port=80

networks:
  traefik:
    external: true
