services:
  frps:
    image: snowdreamtech/frps:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/docker-compose/frp/frps/frps.toml:/etc/frp/frps.toml
    network_mode: host
    restart: unless-stopped
