services:
  watchtower:
    image: containrrr/watchtower:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 7200
    restart: unless-stopped
