services:
  frpc:
    image: snowdreamtech/frpc:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/docker-compose/frp/frpc/frpc.toml:/etc/frp/frpc.toml
    restart: unless-stopped
